export const defaultCategories = [
    "Attack on Titan",
    "Avatar: The Last Airbender",
    "Bleach",
    "Death Note",
    "Demon Slayer",
    "Dragon Ball",
    "Fullmetal Alchemist: Brotherhood",
    "Hunter x Hunter",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Naruto",
    "One Piece",
    "Pokemon",
    "Rick and Morty",
    "Sword Art Online",
    "The Simpsons",
    "Tokyo Ghoul",
];